blank_issues_enabled: true # force the usage of a template
contact_links:
  - name: Feature Requests, support and consulting
    url: petyo.ivanov@icloud.com
    about: I have troubles integrating React Virtuoso in my project and I need dedicated assistance with it.
