name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CI: true
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      USE_SSH: true
      GIT_USER: petyosi
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

    steps:
      - name: Begin CI...
        uses: actions/checkout@v2

      - name: Use Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: yarn install --frozen-lockfile

      - run: yarn install --frozen-lockfile --cwd site

      - run: yarn lint

      - run: yarn test -- --ci 

      - run: yarn e2e -- --ci

      - run: yarn build

      - run: |
          cd site 
          yarn build

      # - name: Configure GH Access
      #   if: github.ref == 'refs/heads/master'
      #   run: |
      #     mkdir -p ~/.ssh
      #     ssh-keyscan github.com >> ~/.ssh/known_hosts
      #     echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_rsa
      #     chmod 600 ~/.ssh/id_rsa
      #     git config --global user.email "underlog@gmail.com"
      #     git config --global user.name "Petyo Ivanov"
      #     cat <<EOT >> ~/.ssh/config
      #     Host github.com
      #     HostName github.com
      #     IdentityFile ~/.ssh/id_rsa
      #     EOT

      # - if: github.ref == 'refs/heads/master'
      #   run: |
      #     echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > .npmrc
      #     yarn pub

      # - name: Deploy docs
      #   if: github.ref == 'refs/heads/master'
      #   run: |
      #     cd packages/docs
      #     yarn deploy
